apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-web
  template:
    metadata:
      name: calculator-app
      labels:
        app: calc-web
    spec:
      containers:
        - name: calculator-app
          image: ari786/calculator:v1.0
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: calc-svc
  namespace: webapps
spec:
  type: NodePort
  selector:
    app: calc-web
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"